<?php
    define($name,$sgpa);
    $scholar=trim(stripslashes(htmlspecialchars($_POST['scholar'])));
    $file=fopen("data.csv",'r');
    $scls=fgetcsv($file);
    $os=0;
    for($i=0;$i<sizeof($scls);$i++)
    {if($scls[$i]==$scholar)
    {$os=$i;
     break;}}
    $scls=fgetcsv($file);
    $name=$scls[$os];
    $scls=fgetcsv($file);
    $sgpa=$scls[$os];
    header("Location:result.php");
   ?>